Fixed for libvpopmail

diff --git a/vqadmin.vpopmail.devel.patch b/vqadmin.vpopmail.devel.patch
--- a/vqadmin.vpopmail.devel.patch
+++ b/vqadmin.vpopmail.devel.patch
@@ -33,23 +33,23 @@
  rm -f vpopusername
  
 -if test ! -f $vpopmaildir/etc/lib_deps
-+if test ! -f /etc/vpopmail/lib_deps
++if test ! -f /etc/libvpopmail/lib_deps
  then
 -        AC_MSG_ERROR(No vpopmail etc/lib_deps file. Upgrade to vpopmail-4.9.8 or above)
-+        AC_MSG_ERROR(No vpopmail /etc/vpopmail/lib_deps file. Install vpopmail-devel-toaster package)
++        AC_MSG_ERROR(No vpopmail /etc/libvpopmail/lib_deps file. Install libvpopmail-devel package)
  fi
 -lib_deps=`cat $vpopmaildir/etc/lib_deps`
-+lib_deps=`cat /etc/vpopmail/lib_deps`
++lib_deps=`cat /etc/libvpopmail/lib_deps`
  AC_SUBST(lib_deps)
  
 -if test ! -f $vpopmaildir/etc/inc_deps
-+if test ! -f /etc/vpopmail/inc_deps
++if test ! -f /etc/libvpopmail/inc_deps
  then
 -        AC_MSG_ERROR(No vpopmail etc/inc_deps file. Upgrade to vpopmail-4.9.8 or above)
-+        AC_MSG_ERROR(No vpopmail /etc/vpopmail/inc_deps file. Install vpopmail-devel-toaster package)
++        AC_MSG_ERROR(No vpopmail /etc/libvpopmail/inc_deps file. Install libvpopmail-devel package)
  fi
 -inc_deps=`cat $vpopmaildir/etc/inc_deps`
-+inc_deps=`cat /etc/vpopmail/inc_deps`
++inc_deps=`cat /etc/libvpopmail/inc_deps`
  AC_SUBST(inc_deps)
  
  cgibindir=""
@@ -88,30 +88,30 @@
  rm -f vpopusername
  
 -if test ! -f $vpopmaildir/etc/lib_deps
-+if test ! -f /etc/vpopmail/lib_deps
++if test ! -f /etc/libvpopmail/lib_deps
  then
 -        { { echo "$as_me:$LINENO: error: No vpopmail etc/lib_deps file. Upgrade to vpopmail-4.9.8 or above" >&5
 -echo "$as_me: error: No vpopmail etc/lib_deps file. Upgrade to vpopmail-4.9.8 or above" >&2;}
-+        { { echo "$as_me:$LINENO: error: No vpopmail /etc/vpopmail/lib_deps file. Install vpopmail-devel-toaster package" >&5
-+echo "$as_me: error: No vpopmail /etc/vpopmail/lib_deps file. Install vpopmail-devel-toaster package" >&2;}
++        { { echo "$as_me:$LINENO: error: No vpopmail /etc/libvpopmail/lib_deps file. Install libvpopmail-devel package" >&5
++echo "$as_me: error: No vpopmail /etc/libvpopmail/lib_deps file. Install libvpopmail-devel package" >&2;}
     { (exit 1); exit 1; }; }
  fi
 -lib_deps=`cat $vpopmaildir/etc/lib_deps`
-+lib_deps=`cat /etc/vpopmail/lib_deps`
++lib_deps=`cat /etc/libvpopmail/lib_deps`
  
  
 -if test ! -f $vpopmaildir/etc/inc_deps
-+if test ! -f /etc/vpopmail/inc_deps
++if test ! -f /etc/libvpopmail/inc_deps
  then
 -        { { echo "$as_me:$LINENO: error: No vpopmail etc/inc_deps file. Upgrade to vpopmail-4.9.8 or above" >&5
 -echo "$as_me: error: No vpopmail etc/inc_deps file. Upgrade to vpopmail-4.9.8 or above" >&2;}
-+        { { echo "$as_me:$LINENO: error: No vpopmail /etc/vpopmail/inc_deps file. Install vpopmail-devel-toaster package" >&5
-+echo "$as_me: error: No vpopmail /etc/vpopmail/inc_deps file. Install vpopmail-devel-toaster package" >&2;}
++        { { echo "$as_me:$LINENO: error: No vpopmail /etc/libvpopmail/inc_deps file. Install libvpopmail-devel package" >&5
++echo "$as_me: error: No vpopmail /etc/libvpopmail/inc_deps file. Install vpopmail-devel package" >&2;}
     { (exit 1); exit 1; }; }
  fi
 -inc_deps=`cat $vpopmaildir/etc/inc_deps`
 -
-+inc_deps=`cat /etc/vpopmail/inc_deps`
++inc_deps=`cat /etc/libvpopmail/inc_deps`
  
  cgibindir=""
  wwwroot=""
